spring:
  application:
    name: client-4

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
    healthCheck:
      enabled: true

server:
  servlet:
    context-path: /client4
  port: 8004
  # port: 8044