spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: client1
          uri: lb://client-1
          predicates:
            - Path=/client1/**
        - id: client3
          uri: lb://client-3
          predicates:
            - Path=/client3/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

server:
  port: 8080