spring:
  application:
    name: client-2
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    metadata-map:
      version: 1
      # version: 2

server:
  port: 8002
  # port: 8022