spring:
  application:
    name: client-1
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:product;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    dynamic:
      seata: true
  sql:
    init:
      enabled: true
      schema-locations: classpath:init_data.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    metadata-map:
      version: 1
      # version: 2

server:
  port: 8001
  # port: 8011