spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
      # defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

server:
  port: 8761
  # port: 8762