spring:
  application:
    name: client-3
  config:
    import: optional:configserver:http://localhost:8888
        
eureka:
  instance:
    metadata-map:
      version: 1
      # version: 2

server:
  port: 8003
  # port: 8033