spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/masakiii03/config-repo
          # username: ${USER_NAME}
          # password: ${PASSWORD}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

server:
  port: 8888